routes/web.php
<?php

Route::middleware(['web', 'auth'])
    ->namespace('Rapture\FreshbooksClassic\Controllers')
    ->prefix('dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::get('freshbooks/import', 'ImportController@index')->name('freshbooks.import');
        Route::get('freshbooks/sales', 'ClientSalesController@index')->name('freshbooks.sales');
        Route::get('freshbooks/category', 'SalesByCategoryController@index')->name('freshbooks.category');
        Route::get('freshbooks/expenses', 'ExpensesController@index')->name('freshbooks.expenses');
    });

Route::middleware(['web', 'auth'])
    ->namespace('Rapture\FreshbooksClassic\Controllers\Imports')
    ->prefix('dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::get('freshbooks/import/categories', 'CategoriesController@store')->name('import.categories');
        Route::get('freshbooks/import/clients', 'ClientsController@store')->name('import.clients');
        Route::get('freshbooks/import/invoices', 'InvoicesController@store')->name('import.invoices');
        Route::get('freshbooks/import/expenses', 'ExpensesController@store')->name('import.expenses');
    });

resources/views/clients/company.blade.php
<div class="form-field">
    <label for="client-address">Address</label>
    <input type="email" name="address" id="client-address" value="{{ old('address') }}">
</div>
<div class="row form-field">
    <div class="w6">
        <label for="client-city">City</label>
        <input type="text" name="city" id="client-city" value="{{ old('city') }}">
    </div>
    <div class="w3">
        <label for="client-province">Province</label>
        <input type="text" name="region" id="client-province" value="{{ old('region') }}">
    </div>
    <div class="w3">
        <label for="client-postal">Postal Code</label>
        <input type="text" name="postal" id="client-postal" value="{{ old('postal') }}">
    </div>
</div>

resources/views/clients/create.blade.php
<div class="widget">
    <div class="form-field">
        <label><em class="far fa-link"></em>Freshbooks Account</label>
        <select name="freshbooks_id" id="freshbooksId">
            <option value="">- Create Account -</option>
            @foreach ($accounts as $account)
            <option value="{{ $account->id }}">{{ $account->name }}</option>
            @endforeach
        </select>
    </div>
</div>

resources/views/clients/edit.blade.php
<div class="widget">
    <div class="form-field">
        <label><em class="far fa-link"></em>Freshbooks Account</label>
        <select name="freshbooks_id" id="freshbooksId">
            <option value="">- Disconnected -</option>
            @foreach ($accounts as $account)
            <option value="{{ $account->id }}"{{ $client->id === $account->client_id ? ' selected' : '' }}>{{ $account->name }}</option>
            @endforeach
        </select>
    </div>
</div>

resources/views/dashboard/alpha-sales.blade.php
@extends('rapture::layouts.dashboard')

@section('title', __('freshbooks::package.sales'))

@section('content')
    @heading
        @lang('freshbooks::package.plural')

        @slot('after')
            <ul class="sales-filters">
                <li class="active"><a href="{{ route('dashboard.freshbooks.sales') }}?type=alpha">Alphabetically</a></li>
                <li><a href="{{ route('dashboard.freshbooks.sales') }}?type=manager">By Manager</a></li>
            </ul>
        @endslot
    @endheading

    @statuses

    <div class="container">
        <!-- <div>Display mode (Month / Quarter / Year / Custom)</div> -->
        <!-- <div>Filters (Spend / Category)</div> -->

        <div class="flex filter-box">
            <form action="" method="get" class="flex spending">
                <select name="outcome">
                    <option value="over">Spent Over</option>
                    <!-- <option value="under">Spent Under</option> -->
                    <!-- <option value="">Spends Between</option> -->
                </select>
                <input type="text" name="spend">
                <select name="term">
                    <option value="month">Per Month</option>
                    <option value="year">Per Year</option>
                    <option value="overall">Overall</option>
                </select>
                <button type="submit" class="btn muted">Filter</button>
            </form>

            <form action="" method="get" class="flex date-range">
                <datepicker name="start" value=""></datepicker>
                <em class="far fa-arrows-h"></em>
                <datepicker name="end" value=""></datepicker>
                <button type="submit" class="btn muted">Filter</button>
            </form>
        </div>

        <table class="table striped">
            <tr>
                <th>@lang('rapture::field.name')</th>
                @foreach ($intervals as $name)
                    <th>{!! $name !!}</th>
                @endforeach
            </tr>
            @foreach ($invoices as $client_id => $invoice)
                <tr>
                    <td>{{ $clients[$client_id] }}</td>
                    @foreach ($intervals as $key => $name)
                        <td>{{ $invoice->has($key) ? '$' . number_format($invoice->get($key) / 100, 2) : '--' }}</td>
                    @endforeach
                </tr>
            @endforeach
        </table>
    </div>
@endsection

@resource('datepicker')

@push('styles')
    <link rel="stylesheet" href="{{ asset('freshbooks/css/style.css') }}">
@endpush

resources/views/dashboard/manager-sales.blade.php
@extends('rapture::layouts.dashboard')

@section('title', __('freshbooks::package.sales'))

@section('content')
    @heading
        @lang('freshbooks::package.plural')

        @slot('after')
            <ul class="sales-filters">
                <li><a href="{{ route('dashboard.freshbooks.sales') }}?type=alpha">Alphabetically</a></li>
                <li class="active"><a href="{{ route('dashboard.freshbooks.sales') }}?type=manager">By Manager</a></li>
            </ul>
        @endslot
    @endheading

    @statuses

    <div class="container">
        @foreach ($users as $user)
            <h3>{{ $user->name }}</h3>

            <table class="table striped">
                <tr>
                    <th>@lang('rapture::field.name')</th>
                    @foreach ($months as $name)
                        <th>{!! $name !!}</th>
                    @endforeach
                </tr>
                @foreach ($invoices->get($user->id) as $group)
                    <tr>
                        <td>{{ $clients[$group['client_id']] }}</td>
                        @foreach ($months as $key => $name)
                            <td>{{ $group['items']->has($key) ? '$' . number_format($group['items']->get($key)->sum('total') / 100, 2) : '--' }}</td>
                        @endforeach
                    </tr>
                @endforeach
                <tr>
                    <td><strong>Total</strong></td>
                    @foreach ($months as $key => $name)
                        <td><strong>{{ $totals->get($user->id)->has($key) ? '$' . number_format($totals->get($user->id)->get($key)->sum('total') / 100, 2) : '--' }}</strong></td>
                    @endforeach
                </tr>
            </table>
        @endforeach
    </div>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('freshbooks/css/style.css') }}">
@endpush

resources/views/expenses/index.blade.php
@extends('rapture::layouts.dashboard')

@section('title', 'Expenses')

@section('content')
    @heading
        Expenses
    @endheading

    @statuses

    <div class="container">
        <table class="table striped">
            <tr>
                <th></th>
                <th>Expenses</th>
            </tr>
            @foreach ($expenses as $key => $group)
                <tr>
                    <td>{{ $key }}</td>
                    <td>
                        @foreach ($group as $label => $amount)
                            @if (!$loop->first)
                                <br>
                            @endif
                            {{ $label }}: ${{ number_format($amount / 100) }}
                        @endforeach
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('freshbooks/css/style.css') }}">
@endpush

resources/views/import/index.blade.php
@extends('rapture::layouts.dashboard')

@section('title', __('freshbooks::package.import'))

@section('content')
    @heading
        @lang('freshbooks::package.import')

        @slot('after')
            Last ran: {{ is_null($lastRun) ? 'Never' : $lastRun->format('Y/m/d g:i a') }}
        @endslot
    @endheading

    @statuses

    <div class="container">
        @if (is_null($lastRun))
        <freshbooks-import></freshbooks-import>
        @else
        <freshbooks-import since="{{ $lastRun->format('Y-m-d') }}"></freshbooks-import>
        @endif
    </div>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('freshbooks/css/style.css') }}">
@endpush

@push('components')
    <script src="{{ asset('freshbooks/js/freshbooks.js') }}"></script>
@endpush

resources/views/sales/index.blade.php
@extends('rapture::layouts.dashboard')

@section('title', 'Sales by Department')

@section('content')
    @heading
        Sales by Department
    @endheading

    @statuses

    <div class="container">
        <table class="table striped">
            <tr>
                <th></th>
                <th>Print</th>
                <th>Graphics</th>
                <th>Web</th>
                <th>Social</th>
                <th>SEM</th>
                <th>Other</th>
            </tr>
            @foreach ($lineItems as $key => $totals)
                <tr>
                    <td>{{ $key }}</td>
                    <td>${{ number_format($totals['print'] / 100) }}</td>
                    <td>${{ number_format($totals['graphics'] / 100) }}</td>
                    <td>${{ number_format($totals['web'] / 100) }}</td>
                    <td>${{ number_format($totals['social'] / 100) }}</td>
                    <td>${{ number_format($totals['sem'] / 100) }}</td>
                    <td>${{ number_format($totals['other'] / 100) }}</td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('freshbooks/css/style.css') }}">
@endpush